package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill dao = new Bill();
}
