package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseClub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Club extends BaseClub<Club> {
	public static final Club dao = new Club();
}
