package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict();
}
