package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseGtsafeDf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GtsafeDf extends BaseGtsafeDf<GtsafeDf> {
	public static final GtsafeDf dao = new GtsafeDf();
}
