package win.yulongsun.jfinal_club.model;

import com.jfinal.plugin.activerecord.Page;
import win.yulongsun.jfinal_club.model.base.BaseMember;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
    public static final Member dao = new Member();

    public Page<Member> paginateByCId(String c_id, int page_num, int page_size) {
        return paginate(page_num, page_size, "SELECT *", "FROM `member` WHERE c_id = ? and c_id !=0 and is_enable !=0", c_id);
    }

    public List<Member> findByName(String member_name, String member_club_id) {
        return find("SELECT * FROM member WHERE `name` like ? AND c_id =?;", "%" + member_name + "%", member_club_id);
    }

    public Member findByMobile(String member_mobile) {
        return findFirst("SELECT * FROM member WHERE mobile = ? ;", member_mobile);
    }

    public Member findByCardId(String card_id, String user_c_id) {
        return findFirst("SELECT * FROM member WHERE card_id = ? and c_id =?;", card_id, user_c_id);
    }
}
