package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();
}
