package win.yulongsun.jfinal_club.model;

import com.jfinal.plugin.activerecord.Page;
import win.yulongsun.jfinal_club.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
    public static final Order dao = new Order();

    public Page<Order> paginateByCId(String c_id, int page_num, int page_size) {
        return paginate(page_num, page_size, "SELECT *", "FROM `order` WHERE c_id = ? ", c_id);
    }
}
