package win.yulongsun.jfinal_club.model;

import win.yulongsun.jfinal_club.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
