package win.yulongsun.jfinal_club.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDictName(java.lang.String dictName) {
		set("dict_name", dictName);
	}

	public java.lang.String getDictName() {
		return get("dict_name");
	}

	public void setKey(java.lang.Integer key) {
		set("key", key);
	}

	public java.lang.Integer getKey() {
		return get("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
